#!/usr/bin/env python3
"""
Phase 4: Translate all Chinese text in 5 remaining hub pages
to Brazilian Portuguese. This is a comprehensive word-by-word
translation of Chinese phrases found in the hub page body content.

Translation approach:
- Chinese phrases are embedded in HTML content of these 5 hub pages:
  * iniciante.html (113 CJK chars, 89 unique phrases)
  * topicos-populares.html (199 CJK chars, 136 unique phrases)
  * membros.html (125 CJK chars, 88 unique phrases)
  * atualizacoes-mensais.html (132 CJK chars, 98 unique phrases)
  * atualizacoes-semanais.html (94 CJK chars, 79 unique phrases)

Strategy: We translate content paragraphs that are in Chinese,
and also fix Chinese phrases embedded in existing PT-BR text.
"""

import re
import os
from pathlib import Path

BASE = Path(r'C:\Users\Lenovo\osrs-guide-site\pt-br')
HUBS = [
    'iniciante.html',
    'topicos-populares.html',
    'membros.html',
    'atualizacoes-mensais.html',
    'atualizacoes-semanais.html',
]

# Comprehensive Chinese → Brazilian Portuguese translation map
# Sorted by priority: longer phrases first to avoid partial matches
CN2PT = {
    # === iniciante.html ===
    "新手起步": "Começando do Zero",
    "新手指南": "Guia para Iniciantes",
    "从零开始": "Do Zero",
    "从零": "Do Zero",
    "零基础": "Iniciante",
    "第一个百万": "Seu Primeiro Milhão",
    "你的第一个百万来自这里": "Seu primeiro milhão começa aqui",
    "赚取第一桶金": "Ganhando seu primeiro dinheiro",
    "开始做": "Comece a fazer",
    "开始打": "Comece a lutar",
    "第一步": "Primeiro Passo",
    "第一个": "O primeiro",
    "第": "Nº",
    "一周之后": "Uma semana depois",
    "周之后": "semanas depois",
    "周后自信探索整个": "semanas depois explorando todo o",
    "周成长": "Crescimento semanal",
    "天": "dias",
    "全部": "Tudo",
    "全收录": "Completo",
    "内容": "Conteúdo",
    "入门": "Introdução",
    "入会后第一时间做的": "O que fazer logo ao entrar",
    "必读": "Leitura Obrigatória",
    "必做": "Obrigatório fazer",
    "必备插件推荐": "Plugins essenciais recomendados",
    "先读这个": "Leia isto primeiro",
    "先看这个": "Veja isto primeiro",
    "从杀手到": "De iniciante a",
    "打造战斗角色": "Construindo seu personagem de combate",
    "战斗": "Combate",
    "战斗入门": "Introdução ao combate",
    "理解战斗三角形": "Entendendo o triângulo de combate",
    "掌握基础操作": "Dominando as operações básicas",
    "熟悉界面": "Familiarizando-se com a interface",
    "导航和核心游戏机制": "Navegação e mecânicas centrais",
    "核心": "Central",
    "核心游戏机制": "Mecânicas centrais do jogo",
    "挂机": "AFK",
    "低等级": "Baixo nível",
    "低成本": "Baixo custo",
    "最高效": "Mais eficiente",
    "最快升级": "Nível mais rápido",
    "升级": "Nível",
    "升级顺序": "Ordem de nível",
    "最快": "Mais rápido",
    "老玩家回归": "Regresso de veteranos",
    "全新的": "Novo",
    "老玩家": "Jogador veterano",
    "回归": "Regresso",
    "进入": "Entrando",
    "深入": "Aprofundando",
    "深入解析": "Análise profunda",
    "详解": "Explicação detalhada",
    "系统详解": "Explicação detalhada do sistema",
    "系统": "Sistema",
    "开启": "Começando",
    "解锁": "Desbloqueando",
    "获取": "Obtendo",
    "购买": "Comprando",
    "购买优先级": "Prioridade de compra",
    "适合": "Adequado para",
    "适合新手": "Adequado para iniciantes",
    "适合你": "Adequado para você",
    "阶段": "Fase",
    "打造": "Construindo",
    "专精": "Especialização",
    "到百万富翁": "a milionário",
    "到中国玩家": "para jogadores chineses",
    "中国玩家": "Jogadores chineses",
    "中国玩家注册与": "Registro de jogadores chineses e",
    "安装与汉化": "Instalação e tradução",
    "安装": "Instalação",
    "汉化": "Tradução chinesa",
    "这件事": "esta coisa",
    "件事": "coisa",
    "新": "Novo",
    "新手": "Iniciante",
    "接下来做什么": "O que fazer a seguir",
    "看一下": "Dê uma olhada",
    "查看全部": "Ver tudo",
    "查看": "Ver",
    "排行榜": "Ranking",
    "排行": "Ranking",
    "你的": "Seu",
    "不是梦": "não é um sonho",
    "真正的冒险从此开始": "Sua verdadeira aventura começa aqui",
    "这是你冒险之旅的起点": "Este é o ponto de partida da sua aventura",
    "起点": "Ponto de partida",
    "这条": "Este",
    "这条路": "Este caminho",
    "与": "e",
    "与策略": "e estratégia",
    "物尽其用": "aproveitar ao máximo",
    "每一步都物尽其用": "Aproveite ao máximo cada passo",
    "省千万": "economize milhões",
    "完全": "Completamente",
    "完全攻略": "Guia completo",
    "完成前": "antes de completar",
    "完成": "Completar",
    "前必做的": "obrigatório antes de",
    "前必做": "obrigatório antes",
    "带你用最高效的方式完成": "Leve você a completar da maneira mais eficiente",
    "最快升级": "Nível mais rápido",
    "最快升级顺序": "Ordem de nível mais rápida",
    "术语表": "Glossário",
    "术语": "Terminologia",
    "无需": "Sem necessidade de",
    "无需顶级": "Sem necessidade de equipamento top",
    "无需会员": "Sem necessidade de membro",
    "团本": "Raid",
    "团本攻略": "Guia de Raid",
    "图": "Mapa",
    "大全": "Enciclopédia",
    "掉落": "Drops",
    "祷告": "Oração/Prayer",
    "祷告入门": "Introdução à Oração",
    "世界": "Mundo",
    "个": "",
    "专题": "Especial",
    "专栏": "Coluna",
    "的": "da",
    "的攻略": "do guia",
    "关键": "chave",
    "的关键": "a chave para",
    "目标": "Objetivo",
    "目标是什么": "Qual é o objetivo",
    "翻赚": "Lucro",
    "翻赚攻略": "Guia de lucro",
    "URN": "URL",
    "物品与": "Itens e",
    "物品": "Itens",
    "角色养成": "Desenvolvimento de personagem",

    # === topicos-populares.html ===
    "热门话题": "Tópicos Populares",
    "热门话题精选": "Tópicos Populares em Destaque",
    "话题": "Tópico",
    "精选": "Em destaque",
    "精选的中国玩家最关心的热门话题": "Tópicos populares selecionados que jogadores chineses mais se preocupam",
    "热门": "Popular",
    "讨论精选的中国玩家最关心的": "Discussão sobre tópicos populares selecionados que jogadores chineses mais se preocupam",
    "为": "para",
    "为巴西玩家": "para jogadores brasileiros",
    "为新手": "para iniciantes",
    "中国": "China",
    "中文": "Chinês",
    "不浪费一分钱": "Sem desperdiçar um centavo",
    "上线": "Lançamento",
    "即将上线": "Em breve",
    "上线时间": "Horário de lançamento",
    "为新手准备": "Preparado para iniciantes",
    "为老玩家": "para jogadores veteranos",
    "为F2P": "para F2P",
    "为P2P": "para P2P",
    "一件事": "uma coisa",
    "中级": "Nível intermediário",
    "高级": "Nível avançado",
    "从": "De",
    "从最低要求到": "Das exigências mínimas a",
    "从被人秒到反杀的全部基础": "Todas as bases de ser morto instantaneamente a revidar",
    "从零打造最强": "Construindo o mais forte do zero",
    "从零打造": "Construindo do zero",
    "从零开始": "Começando do zero",
    "从新手到": "De iniciante a",
    "从入门到精通": "De iniciante a mestre",
    "件必做": "coisas obrigatórias a fazer",
    "全是干货": "Tudo é conteúdo útil",
    "全是": "Tudo é",
    "干货": "conteúdo útil",
    "全部简单和中等成就日记最优完成顺序": "Ordem ótima para completar todos os diários de conquistas simples e médios",
    "全部简单和中等成就日记": "Todos os diários de conquistas simples e médios",
    "简单": "Simples",
    "中等": "Médio",
    "中等难度": "Dificuldade média",
    "简单和中等": "Simples e médios",
    "精英": "Elite",
    "困难和精英成就日记的高效完成": "Conclusão eficiente de diários de conquistas difíceis e de elite",
    "困难": "Difícil",
    "精英等高奖励日记的最优策略和最低属性要求": "Melhor estratégia e exigências mínimas de atributos para diários de alta recompensa como elite",
    "精英难度": "Dificuldade de elite",
    "成就日记": "Diário de Conquistas",
    "成就": "Conquistas",
    "日记": "Diário",
    "日记的": "do Diário",
    "入手顺序和性价比分析": "Ordem de aquisição e análise de custo-benefício",
    "入手顺序": "Ordem de aquisição",
    "性价比分析": "Análise de custo-benefício",
    "性价": "custo-benefício",
    "也": "também",
    "也能参与": "também pode participar",
    "列表": "Lista",
    "到": "a",
    "到中期": "ao estágio intermediário",
    "到常客": "a jogador frequente",
    "到航海": "a navegação",
    "到终局": "ao endgame",
    "中期到终局": "Do intermediário ao endgame",
    "中期": "Intermediário",
    "终局": "Endgame",
    "前置": "Pré-requisito",
    "前置任务": "Pré-requisitos de missão",
    "午休": "Pausa para almoço",
    "号": "conta",
    "各类型": "Todos os tipos",
    "各类型Boss": "Todos os tipos de Boss",
    "基于": "Baseado em",
    "基于玩家反馈和": "Baseado em feedback de jogadores e",
    "提供": "Fornecendo",
    "提供什么": "O que fornece",
    "搭配全解析": "Análise completa de combinações",
    "搭配": "Combinação",
    "搭配方案": "Esquema de combinação",
    "奖励表": "Tabela de recompensas",
    "奖励": "Recompensa",
    "姿势": "Postura",
    "完全攻略": "Guia completo",
    "官方": "Oficial",
    "官方攻略": "Guia oficial",
    "官方推荐": "Recomendado oficialmente",
    "小时分析": "Análise de hora",
    "小时": "hora",
    "屠龙者": "Matador de dragões",
    "屠龙": "Matar dragão",
    "年": "ano",
    "年全部": "Tudo do ano",
    "2025年": "Ano 2025",
    "2026年": "Ano 2026",
    "必做清单": "Lista de coisas obrigatórias a fazer",
    "必学的切装": "Troca de equipamento obrigatória a aprender",
    "必学": "Obrigatório aprender",
    "切装": "Troca de equipamento",
    "切装基础": "Básico de troca de equipamento",
    "性能设置": "Configurações de desempenho",
    "设置": "Configuração",
    "手机版": "Versão mobile",
    "手机版最适合做的": "O que é mais adequado fazer na versão mobile",
    "手机版设置": "Configuração da versão mobile",
    "手机版高效刷怪": "Farming eficiente na versão mobile",
    "打法": "Estratégia de combate",
    "打法详解": "Explicação detalhada da estratégia de combate",
    "打法攻略": "Guia de estratégia de combate",
    "挂机攻略": "Guia de farming AFK",
    "换装": "Troca de equipamento",
    "无关联": "Sem associação",
    "无关联话题": "Tópicos sem associação",
    "日": "dia",
    "月": "mês",
    "时机": "Timing",
    "时机选择": "Escolha de timing",
    "最快完成": "Completar o mais rápido possível",
    "最适合": "Mais adequado",
    "最适合新手": "Mais adequado para iniciantes",
    "有想看的主题": "Tem um tópico que quer ver",
    "本站与": "Este site e",
    "本站与Jagex": "Este site e a Jagex",
    "每一步都物尽其用": "Aproveite ao máximo cada passo",
    "沙漠宝藏": "Deserto Tesouro",
    "沙漠": "Deserto",
    "热门话题写成": "Tópicos populares escritos como",
    "物品清单": "Lista de itens",
    "独特掉落价值": "Valor único de drop",
    "独特": "Único",
    "掉落价值": "Valor de drop",
    "界面优化": "Otimização de interface",
    "界面布局优化": "Otimização de layout de interface",
    "界面": "Interface",
    "界面布局": "Layout de interface",
    "的升级": "de nível",
    "的各阶段": "de cada fase",
    "的商标": "® marca registrada",
    "的团本": "do Raid",
    "的必经之路": "o caminho obrigatório para",
    "的航海": "da Navegação",
    "的超": "do ultra",
    "目前最": "Atualmente o mais",
    "睡前的": "Antes de dormir",
    "睡前的必做": "Obrigatório fazer antes de dormir",
    "砍树": "Cortar árvores",
    "积分系统": "Sistema de pontos",
    "第一个团本": "O primeiro Raid",
    "篇新": "novos artigos",
    "篇": "artigo",
    "精选的中国玩家最关心的热门话题": "Tópicos populares selecionados que os jogadores chineses mais se preocupam",
    "系统": "Sistema",
    "组队建议": "Sugestão de grupo",
    "航海": "Navegação",
    "航海专属": "Exclusivo para navegação",
    "航海全": "Navegação completa",
    "航海全攻略": "Guia completo de navegação",
    "船体升级": "Upgrade do casco",
    "船体升级全": "Upgrade completo do casco",
    "要求和奖励详解": "Explicação detalhada de exigências e recompensas",
    "要求": "Exigência",
    "解锁神话披风的关键一步": "Um passo chave para desbloquear a Capa Mítica",
    "解锁远古魔法和顶级": "Desbloquear magia ancestral e top",
    "触控操作": "Operação por toque",
    "账号": "Conta",
    "账号养成完全": "Desenvolvimento completo de conta",
    "账号养成": "Desenvolvimento de conta",
    "货物运输": "Transporte de carga",
    "贸易": "Comércio",
    "资源采集": "Coleta de recursos",
    "选择": "Escolha",
    "选择和": "Escolha e",
    "逐步通关": "Passando de nível gradualmente",
    "通关": "Passando de nível",
    "通勤": "Trajeto",
    "通勤路上的": "no trajeto",
    "邮箱": "E-mail",
    "钓鱼": "Pescaria",
    "阅读": "Leitura",
    "食物时机": "Timing de comida",

    # === membros.html ===
    "会员指南": "Guia de Membros",
    "会员": "Membros",
    "会员攻略": "Guia de Membros",
    "一站式": "Tudo-em-um",
    "不会增加您的任何费用": "Não aumentará nenhum custo para você",
    "与": "e",
    "专业提示": "Dica profissional",
    "价格": "Preço",
    "价格与省钱": "Preço e economia",
    "价格分析": "Análise de preço",
    "价格波动的应对策略": "Estratégia de resposta a flutuações de preço",
    "涨价": "Aumento de preço",
    "涨价分析": "Análise de aumento de preço",
    "涨价后": "Após o aumento de preço",
    "涨价详情": "Detalhes do aumento de preço",
    "值不值": "Vale a pena ou não",
    "值得买吗": "Vale a pena comprar?",
    "地区定价": "Preços regionais",
    "地区": "Regional",
    "全球比价": "Comparação de preços global",
    "全部资源汇总": "Resumo de todos os recursos",
    "全面": "Abrangente",
    "全面解析": "Análise abrangente",
    "关于": "Sobre",
    "关于本站": "Sobre este site",
    "养殖": "Farming",
    "养殖成为最省钱方案": "Farming tornando-se a opção mais econômica",
    "分析": "Análise",
    "分钟": "minutos",
    "功能": "Funcionalidade",
    "和": "e",
    "和地区定价": "e preços regionais",
    "哪个更划算": "Qual é mais vantajoso",
    "哪些最值得优先练": "Quais valem mais a pena priorizar",
    "商标": "® marca registrada",
    "回报率": "Taxa de retorno",
    "地图": "Mapa",
    "帮你决定要不要买": "Ajudando você a decidir se deve comprar",
    "微信支付": "WeChat Pay",
    "支付宝": "Alipay",
    "本站可能包含联盟链接": "Este site pode conter links de afiliados",
    "我们可能获得小额佣金": "Podemos receber uma pequena comissão",
    "拿到最低价": "Obter o preço mais baixo",
    "直接": "Direto",
    "相关分类": "Categorias relacionadas",
    "省钱": "Economia",
    "省钱方案": "Plano de economia",
    "真金白银的成本": "Custo real em dinheiro",
    "第一个": "O primeiro",
    "第一天的高效清单": "Lista eficiente do primeiro dia",
    "联系我们": "Contate-nos",
    "获取策略": "Estratégia de obtenção",
    "行动": "Ação",
    "详解": "Explicação detalhada",
    "购买": "Compra",
    "费用": "Custo",
    "资源": "Recurso",
    "转": "transformar",
    "量化": "Quantificação",
    "铁人模式": "Modo Ironman",
    "铁人最需要的": "O que Ironman mais precisa",
    "铁人模式优先练": "Priorizar treinar no Modo Ironman",
    "链接": "Link",
    "首": "primeiro",

    # === atualizacoes-mensais.html ===
    "更新": "Atualização",
    "更新月报": "Relatório mensal de atualizações",
    "一个月内三大": "Três grandes em um mês",
    "一网打尽": "Tudo de uma vez",
    "中文详解": "Explicação detalhada em chinês",
    "中文": "Chinês",
    "为": "para",
    "今夏": "Este verão",
    "优化你的": "Otimizando seu",
    "保留所有权利": "Todos os direitos reservados",
    "制作": "Produzido por",
    "全": "Completo",
    "剧情评分": "Avaliação do enredo",
    "单人": "Solo",
    "即将上线": "Em breve",
    "发布中文详解": "Publicar explicação detalhada em chinês",
    "发布后": "Após a publicação",
    "变化": "Mudança",
    "变化详解": "Explicação detalhada das mudanças",
    "变弱了": "Enfraquecido",
    "变强": "Fortalecido",
    "号": "conta",
    "同步发布": "Publicação síncrona",
    "后": "depois",
    "含铁人模式建议": "Com sugestões para Modo Ironman",
    "吸血鬼王国": "Vampyrium",
    "和": "e",
    "哪些": "Quais",
    "四种": "Quatro tipos",
    "回来看看": "Volte para dar uma olhada",
    "常回来看看": "Volte frequentemente para dar uma olhada",
    "夏日清扫": "Limpeza de Verão",
    "夏日清扫后账号重建策略": "Estratégia de reconstrução de conta após a Limpeza de Verão",
    "大常见死法及规避": "10 mortes comuns e como evitá-las",
    "大改": "Grande reformulação",
    "大神级": "Nível de mestre",
    "如何利用这次": "Como aproveitar esta",
    "完全": "Completo",
    "官方": "Oficial",
    "定期": "Regularmente",
    "小时内": "dentro de horas",
    "小时内出中文详解": "Explicação detalhada em chinês dentro de horas",
    "小时内发布中文详细解读": "Publicar interpretação detalhada em chinês dentro de horas",
    "山羊狩猎": "Caça de Cabra",
    "已上线": "Já lançado",
    "常回来看看": "Volte frequentemente para dar uma olhada",
    "年": "ano",
    "年全部": "Tudo do ano",
    "年夏季": "Verão do ano",
    "年度最大": "O maior do ano",
    "想第一时间收到": "Quer receber na primeira hora",
    "掌握": "Dominar",
    "提供": "Fornecer",
    "搭配方案": "Plano de combinação",
    "收藏此页面": "Favorite esta página",
    "数据源自": "Dados provenientes de",
    "新": "Novo",
    "新区域": "Nova área",
    "新岛": "Nova ilha",
    "新杀手大师": "Novo Slayer Master",
    "新的": "Novo",
    "新资源": "Novo recurso",
    "无关联": "Sem associação",
    "日": "dia",
    "日上线": "Lançado no dia",
    "最快": "O mais rápido",
    "月": "mês",
    "本月": "Este mês",
    "本月上新": "Novidades deste mês",
    "本站与": "Este site e",
    "机制深度解析": "Análise profunda da mecânica",
    "条新捷径": "novos atalhos",
    "每期": "Cada edição",
    "每次": "Cada vez",
    "深度解析": "Análise profunda",
    "热门": "Popular",
    "版本改动一网打尽": "Todas as mudanças de versão de uma vez",
    "猎人体验优化": "Otimização da experiência de Slayer",
    "玩家痛点终结者": "O fim das dores de cabeça dos jogadores",
    "由玩家设计的新岛": "Nova ilha projetada por jogadores",
    "疯狂天使": "Anjo Louco",
    "的商标": "® marca registrada",
    "真实可靠": "Verdadeiro e confiável",
    "矩阵": "Matriz",
    "策略": "Estratégia",
    "系列终章": "Capítulo final da série",
    "联系我们": "Contate-nos",
    "航海": "Navegação",
    "航海扩展": "Expansão de navegação",
    "船体升级": "Upgrade do casco",
    "船体升级全": "Upgrade completo do casco",
    "蛆虫之王": "Rei das Larvas",
    "血月崛起": "Ascensão da Lua Sangrenta",
    "详解": "Explicação detalhada",
    "购买优先级": "Prioridade de compra",
    "近年来最大的": "O maior dos últimos anos",
    "返回": "Voltar",
    "通知": "Notificação",
    "邮箱": "E-mail",
    "错过任何一个你都会后悔": "Você vai se arrepender se perder qualquer um",
    "阅读": "Leitura",
    "随夏日清扫": "Com a Limpeza de Verão",
    "预览": "Pré-visualização",

    # === atualizacoes-semanais.html ===
    "一页全掌握": "Tudo em uma página",
    "上线": "Lançamento",
    "中文站": "Site chinês",
    "为": "para",
    "五": "5ª",
    "五准时发布": "Publicação pontual na 5ª",
    "五发布": "Publicação na 5ª",
    "五新": "Novidades da 5ª",
    "优化": "Otimização",
    "保留所有权利": "Todos os direitos reservados",
    "制作": "Produzido por",
    "全是干货": "Tudo é conteúdo útil",
    "内容": "Conteúdo",
    "准备清单": "Lista de preparação",
    "前置要求": "Pré-requisitos",
    "加强": "Fortalecimento",
    "动态": "Dinâmico",
    "发布新": "Publicar novo",
    "变化": "Mudança",
    "变化和": "Mudanças e",
    "变强变弱一图看懂": "Entenda em um gráfico quem ficou mais forte ou mais fraco",
    "吉埃林诺的": "de Giethinor",
    "吉埃林诺": "Giethinor",
    "周": "semana",
    "和": "e",
    "哪些": "Quais",
    "基于玩家反馈和": "Baseado em feedback de jogadores e",
    "夏日清扫": "Limpeza de Verão",
    "夏日清扫后的全新": "Novo após a Limpeza de Verão",
    "夏日清扫深度": "Profundidade da Limpeza de Verão",
    "大改": "Grande reformulação",
    "大死法及规避": "10 mortes e como evitá-las",
    "大神级": "Nível de mestre",
    "奖励预览": "Pré-visualização de recompensas",
    "山羊狩猎": "Caça de Cabra",
    "已确认的全部信息": "Todas as informações confirmadas",
    "想": "Quer",
    "想第一时间收到": "Quer receber na primeira hora",
    "战前准备": "Preparação pré-combate",
    "抢先看": "Pré-visualização antecipada",
    "推荐": "Recomendado",
    "提供": "Fornecer",
    "搭配方案": "Plano de combinação",
    "搭配矩阵": "Matriz de combinação",
    "收到": "Receber",
    "收藏此页面别错过": "Favorite esta página e não perca",
    "新岛预览": "Pré-visualização da nova ilha",
    "新杀手大师": "Novo Slayer Master",
    "无关联": "Sem associação",
    "无死": "Sem morte",
    "日上线": "Lançado no dia",
    "日": "dia",
    "月": "mês",
    "本周": "Esta semana",
    "本周上新": "Novidades desta semana",
    "本周必看": "Obrigatório ver esta semana",
    "本周热门": "Popular desta semana",
    "本周更新": "Atualização desta semana",
    "本站与": "Este site e",
    "机制全解": "Explicação completa da mecânica",
    "条新敏捷捷径": "novos atalhos de Agilidade",
    "疯狂天使": "Anjo Louco",
    "的商标": "® marca registrada",
    "第": "Nº",
    "策略": "Estratégia",
    "紧跟版本不掉队": "Mantenha-se atualizado sem ficar para trás",
    "联系我们": "Contate-nos",
    "航海扩展": "Expansão de navegação",
    "航海新岛预览": "Pré-visualização da nova ilha de navegação",
    "血月崛起": "Ascensão da Lua Sangrenta",
    "血月崛起准备清单": "Lista de preparação para Ascensão da Lua Sangrenta",
    "购买优先级重排": "Reordenação da prioridade de compra",
    "返回": "Voltar",
    "速通": "Speedrun",
    "邮箱": "E-mail",
    "铁人模式建议": "Sugestão para Modo Ironman",
    "阅读": "Leitura",
    "预览": "Pré-visualização",
}

# Sort by length (longest first) to avoid partial replacements
SORTED_KEYS = sorted(CN2PT.keys(), key=len, reverse=True)


def fix_hub(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original = content
    for phrase in SORTED_KEYS:
        if phrase in content:
            content = content.replace(phrase, CN2PT[phrase])

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False


def count_cn(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    return len(re.findall(r'[\u4e00-\u9fff]', content))


if __name__ == '__main__':
    print('=== Phase 4: Translating 5 hub pages Chinese→PT-BR ===\n')
    total_before = 0
    total_after = 0
    for fname in HUBS:
        fpath = BASE / fname
        before = count_cn(fpath)
        total_before += before
        changed = fix_hub(fpath)
        after = count_cn(fpath)
        total_after += after
        status = 'FIXED' if changed else 'clean'
        print(f'  [{status}] {fname}: {before} -> {after}')

    print(f'\nTotal before: {total_before}')
    print(f'Total after:  {total_after}')
    print(f'Reduction:    {total_before - total_after}')
    print('\nDone!')
